default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: localhost
  port: 3306
  username: <%= ENV["USERNAME_DATABASE"] %>
  password: <%= ENV["PASSWORD_DATABASE"] %>

development:
  <<: *default
  database: <%= ENV["NAME_DATABASE"] %>

test:
  <<: *default
  database: "sample_app_test"

production:
  <<: *default
  database: <%= ENV["NAME_DATABASE"] %>
